## ------------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ------------------------------------------------------------------------------

## ------------------------------------------------------------------------------
## LOGGING SETTINGS CAN BE CHANGED AT RUNTIME WITHOUT RESTARTING THE BROKER.
## SIMPLY EDIT THIS FILE THEN, USING JCONSOLE, LOCATE THE BROKER'S MBEAN
## AND INVOKE ITS 'reloadLog4jProperties' OPERATION.
## ------------------------------------------------------------------------------

## ------------------------------------------------------------------------------
## All logging that reaches the root logger to be sent to the console which in
## turn is hooked by the service wrapper. The service wrapper will handle all
## local file logging and rotation as well as forwarding to syslog, depending
## on the environment. Consequently there is no need to define either a file or
## syslog appender here.
## ------------------------------------------------------------------------------
log4j.rootLogger=INFO, console
log4j.throwableRenderer=org.apache.log4j.EnhancedThrowableRenderer

## ------------------------------------------------------------------------------
## Customized Log4j categories
## ------------------------------------------------------------------------------
log4j.logger.org.apache.xbean=WARN
log4j.logger.org.springframework=WARN
log4j.logger.org.apache.activemq.spring=WARN
log4j.logger.org.apache.activemq.web.handler=WARN
log4j.logger.org.eclipse.jetty=WARN
log4j.logger.org.apache.activemq.broker.jmx=WARN
log4j.logger.org.apache.activemq.store.kahadb.MessageDatabase=WARN
log4j.logger.org.apache.activemq.pool.PooledConnectionFactory=INFO

## ------------------------------------------------------------------------------
## Logger category for TimeStampingBrokerPlugin
## ------------------------------------------------------------------------------
log4j.logger.org.apache.activemq.broker.util.TimeStampingBrokerPlugin=DEBUG

## ------------------------------------------------------------------------------
## Logger category for DiscardingDLQBrokerPlugin
## ------------------------------------------------------------------------------
log4j.logger.org.apache.activemq.plugin.DiscardingDLQBroker=TRACE

## ------------------------------------------------------------------------------
## Logger category for STOMP inactivity monitoring. Used for heart beat debugging.
## ------------------------------------------------------------------------------
log4j.logger.org.apache.activemq.transport.AbstractInactivityMonitor=INFO
log4j.logger.org.apache.activemq.transport.stomp.StompInactivityMonitor=INFO

## ------------------------------------------------------------------------------
## Logger category for lease-database-locker activity.
## ------------------------------------------------------------------------------
log4j.logger.org.apache.activemq.store.jdbc=DEBUG

## ------------------------------------------------------------------------------
## Logger category for Wire Format negotiation activity.
## ------------------------------------------------------------------------------
log4j.logger.org.apache.activemq.transport.WireFormatNegotiator=DEBUG

## ------------------------------------------------------------------------------
## Logger category for failover transport activity.
## ------------------------------------------------------------------------------
log4j.logger.org.apache.activemq.transport.failover.FailoverTransport=DEBUG

## ------------------------------------------------------------------------------
## Logger category for Camel's endpoint message listener.
## ------------------------------------------------------------------------------
log4j.logger.org.apache.camel.component.jms.EndpointMessageListener=ERROR

## ------------------------------------------------------------------------------
## Console appender
## ------------------------------------------------------------------------------
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%-5p | %-30.30c{1} | %m | %t%n

## ------------------------------------------------------------------------------
## MDC (Mapped Diagnostic Context) Logging
##
## See: http://activemq.apache.org/mdc-logging.html
##      http://logback.qos.ch/manual/mdc.html
##
## Use some of the following patterns to see MDC logging data:
##
## %X{activemq.broker}
## %X{activemq.connector}
## %X{activemq.destination}
##
## Example 1:
##  log4j.appender.logfile.layout.ConversionPattern=%d | %-20.20X{activemq.connector} | %-5p | %m | %c | %t%n
##
## Example 2:
##  log4j.appender.logfile.layout.ConversionPattern=%d [%-15.15t] - %-5p %-30.30c{1} - %-10.10X{activemq.broker} %-20.20X{activemq.connector} %-20.20X{activemq.destination} - %m%n
##
## ------------------------------------------------------------------------------

## ------------------------------------------------------------------------------
## Audit logging
##
## Use to log admin events performed through the web-console.
## Example: deleting a queue logs the action as well as the IP of the client
## performing the action.
##
## Always log at the INFO level as very little logging is generated by this.
##
## ------------------------------------------------------------------------------
log4j.appender.audit=org.apache.log4j.RollingFileAppender
log4j.appender.audit.append=true
log4j.appender.audit.file=${activemq.log}/audit.log
log4j.appender.audit.maxFileSize=1MB
log4j.appender.audit.maxBackupIndex=5
log4j.appender.audit.layout=org.apache.log4j.PatternLayout
log4j.appender.audit.layout.ConversionPattern=%d{yyyy/MM/dd HH:mm:ss.SSS} | %-5p | %-30.30c{1} | %m%n

log4j.logger.org.apache.activemq.audit=INFO, audit

## ------------------------------------------------------------------------------
## STOMP logging
## ------------------------------------------------------------------------------
log4j.appender.stomp=org.apache.log4j.RollingFileAppender
log4j.appender.stomp.append=true
log4j.appender.stomp.file=${activemq.log}/stomp.log
log4j.appender.stomp.maxFileSize=25MB
log4j.appender.stomp.maxBackupIndex=5
log4j.appender.stomp.layout=org.apache.log4j.PatternLayout
log4j.appender.stomp.layout.ConversionPattern=%d{yyyy/MM/dd HH:mm:ss.SSS} | %-5p | %-30.30c{1} | %m%n

## ------------------------------------------------------------------------------
## Note:
##   Enable the StompIO logger (disabling the stomp logger) if you want frame IO
##   ONLY, e.g., no heart beating etc.
## ------------------------------------------------------------------------------
#log4j.logger.org.apache.activemq.transport.stomp.StompIO=TRACE, stomp
#log4j.additivity.org.apache.activemq.transport.stomp.StompIO=false
log4j.logger.org.apache.activemq.transport.stomp=TRACE, stomp
log4j.additivity.org.apache.activemq.transport.stomp=false

## ------------------------------------------------------------------------------
## KahaDB logging
## ------------------------------------------------------------------------------
log4j.appender.kahadb=org.apache.log4j.RollingFileAppender
log4j.appender.kahadb.append=true
log4j.appender.kahadb.file=${activemq.log}/kahadb.log
log4j.appender.kahadb.maxFileSize=1024KB
log4j.appender.kahadb.maxBackupIndex=5
log4j.appender.kahadb.layout=org.apache.log4j.PatternLayout
log4j.appender.kahadb.layout.ConversionPattern=%d{yyyy/MM/dd HH:mm:ss.SSS} | %-5p | %-30.30c{1} | %m%n

log4j.logger.org.apache.activemq.store.kahadb.MessageDatabase=TRACE, kahadb
log4j.additivity.org.apache.activemq.store.kahadb.MessageDatabase=false

