#encoding=UTF-8
wrapper.license.type=DEV
wrapper.license.id=201405130005
wrapper.license.licensee=Manheim
wrapper.license.dev_application=ActiveMQ
wrapper.license.features=pro, 64bit
wrapper.license.upgrade_term.begin_date=2014-04-17
wrapper.license.upgrade_term.end_date=2015-04-17
wrapper.license.key.1=3d18-08d4-aa94-f9b5
wrapper.license.key.2=e8f9-efaa-485d-f35c
wrapper.license.key.3=2f2d-33ba-c88c-06a5
wrapper.license.key.4=b40e-d834-0ced-8528
